"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import PyQt5

APP = ['pyRotateDisplayMainMac.py']
OPTIONS = {'argv_emulation': False, 'iconfile':'app_name.icns', 'plist': {'CFBundleShortVersionString':'1.0',"LSUIElement":True}}

QTDIR = r'/opt/local/share/qt5/'
QTCONFDIR = r'/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/py2app/recipes/'
DATA_FILES = [
    "iokit.metadata","iodisp.metadata","Logo.png",
    ("../Resources/qt_plugins/PyQt5", [QTDIR + r'/plugins/PyQt5/libpyqt5qmlplugin.dylib']),
    ("../Resources/qt_plugins/platforms", [QTDIR + r'/plugins/platforms/libqcocoa.dylib',QTDIR + r'/plugins/platforms/libqminimal.dylib',QTDIR + r'/plugins/platforms/libqoffscreen.dylib']),
    ("../Resources/qt_plugins/iconengines", [QTDIR + r'/plugins/iconengines/libqsvgicon.dylib']),
    ("../Resources/qt_plugins/imageformats", [QTDIR + r'/plugins/imageformats/libqsvg.dylib']),
    ("../translations", [QTDIR + r'/translations/qt_ja.qm']),
    ("../Resources", [QTCONFDIR + r'/qt.conf'])
]

setup(
    app=APP,
    name='pyRotateDisplay',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
